apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

# Resources to be deployed
resources:
  - ../../base
  - namespace.yaml

# Apply a patch to modify specific resources
# https://kubectl.docs.kubernetes.io/references/kustomize/patches/
patches:
- path: patch.yaml

# Labels added to all resources in all
# Note : Note: commonLabels should only be set for immutable labels, since they will be applied to Selectors.
# For non-immutable label, use transformers instead
commonLabels:
  variant: staging

# Annotations added to all resources
commonAnnotations:
  variant: staging
  project: helloservice
  tool: kustomize