---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-left-leg
  labels:
    app.kubernetes.io/name: podtato-head
    app.kubernetes.io/component: left-leg
    app.kubernetes.io/version: '0.2.7'
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head
      app.kubernetes.io/component: left-leg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head
        app.kubernetes.io/component: left-leg
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: podtato-head
      containers:
        - name: podtato-head-left-leg
          image: ghcr.io/podtato-head/left-leg:0.2.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources: {}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
