apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

# Resources to be deployed
resources:
  - ../../base
  - namespace.yaml

# You can also point to a remote base with its URL
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#url-format
# resources:
#   - github.com/cncf/podtato-head/delivery/kustomize/base
#   - namespace.yaml